[package]
name = "stylance-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.4.0"
core = { workspace = true }
clap = { version = "4.4.12", features = ["derive"] }
anyhow = "1.0.79"
